name: ${name}
version: ${version}
author: "LetsGoAway"
main: dev.letsgoaway.geyserextras.spigot.GeyserExtrasSpigot
api-version: '1.12'
depend:
  - Geyser-Spigot
commands:
  geyserextras:
    description: Open the GeyserExtras menu.
    usage: /<command>
    aliases:
      - ge
  platformlist:
    description: Shows a player list including everyone's platforms.
    usage: /<command>
    aliases:
      - pl
      - platforms
  playerlist:
    description: Shows the Java Tab Player List menu for Bedrock Edition Players.
    usage: /<command>
    aliases:
      - l
      - players
      - listplayers
      - tab
      - tablist
  emotechat:
    description: Toggles Bedrock Player emote chat for Java Players.
    usage: /<command>
    aliases:
      - muteemotechat
      - unmuteemotechat