# GeyserExtras
# If Geyser-Spigot is detected, all required config changes will be automatically applied.
# For more details, go to https://github.com/GeyserExtras/GeyserExtras/wiki

# Enable the Java Edition styled cooldown.
# Requires show-cooldown: "false" in Geyser's config.
enable-custom-cooldown: true

# Enable the Java Edition combat sounds.
enable-java-combat-sounds: true

# Forces block placements to not be hold-bridgable/scaffold-bridgeable.
# Requires disable-bedrock-scaffolding: true in Geyser's config for forward block placements.
enable-java-only-block-placement: false

# Updates the block at the player's line of sight every tick to remove ghost blocks.
enable-block-ghosting-fix: false

# When the server closes or Geyser reloads, should GeyserExtras reconnect to the server using the below address.
auto-reconnect: true

# This is the ip and port players connect to via any port forwarding system NOT YOUR LOCAL IP. You
# should set this to the ip and port you give to your players.
external-address: "mc.exampleaddress.net"
external-port: 19132

# The actions that will show up in the Quick-Menu. Quick-Menu requires the plugin version of Geyser.
# Actions are formatted as shown below,
# "{title} >> {command}"
# Commands are executed as the player.
# Available placeholders are:

# %player_name% - The name that is the Java Username of the player. For example: .Geyser_Extras
# If the player is linked the linked Java account's name is used.

# %xbox_username% - The username that the Bedrock player has. For example: Geyser Extras

# %player_device% - The device the player is using currently.
# Possible values: Android | iOS | Amazon | Windows Phone | Gear VR | Hololens | Windows | macOS | Apple TV | PlayStation | Switch | Xbox | Dedicated | Unknown

# %player_platform% - The platform the player is using currently.
# Possible values: Console | Mobile | PC | VR | Unknown

# %player_inputtype% - The input type the player is using.
# Possible values: Keyboard | Touch | Controller | VR | Unknown

# %player_uiprofile% - The UI Profile the player is using.
# Possible values: Classic | Pocket
quick-menu-actions:
  - "Swap Items with Off-hand >> /geyser offhand"
  - "Toggle Tooltips >> /geyser tooltips"
  - "Open GeyserExtras Menu >> /ge"
  - "Open Advancements >> /geyser advancements"
  - "Open Statistics >> /geyser statistics"
  - "Player List >> /playerlist"
  - "Platform List >> /platformlist"

# Enables the Knockback Attack Sprint fix.
# In java, when you execute a Knockback attack, the Player stops sprinting for one tick.
# The workaround for Bedrock tricks the client into having no hunger for a tick, however
# this temporarily makes the hunger bar look empty.
enable-knockback-attack-sprint-fix: true

# Enables downloading of Bedrock Player skins.
#  Please note that this is only the skin that Floodgate converts for Java Players meaning
#  that some marketplace skins like 128x128 skins, character creator skins or even some classic skins with weird geometry may not look 100% identical.
enable-skin-saving: false

# Sets the default emote chat option for Java Players.
# The GeyserExtras plugin forwards emote chat from Bedrock Edition to Java Players.
# Java Players can still choose if they want to see emote chat by doing /emotechat
mute-emote-chat: false

# Whether to disable the Paper Doll or not.
# The Paper Doll is the small player graphic in the top left of bedrock players screens
# This can give players a competitve advantage over java in some cases, for example,
# you can see what armor you have on without pressing the inventory key
# you can see what armor has broken during combat
disable-paper-doll: false

# Only enable if you are using GeyserExtras on a proxy.
proxy-mode: false