name: GeyserExtras
version: '1.21.0-v1.1.4'
author: "LetsGoAway"
main: dev.letsgoaway.geyserextras.spigot.GeyserExtras
api-version: '1.21'
softdepend: [floodgate, Geyser-Spigot]
commands:
  geyserextras:
    description: Open the GeyserExtras menu.
    usage: /<command>
    permission: geyserextras.menu
    aliases:
      - ge
  platformlist:
    description: Shows a player list including everyone's platforms.
    usage: /<command>
    permission: geyserextras.platformlist
    aliases:
      - pl
      - platforms
  playerlist:
    description: Shows the Java Tab Player List menu for Bedrock Edition Players.
    usage: /<command>
    permission: geyserextras.playerlist
    aliases:
      - l
      - players
      - listplayers
      - tab
      - tablist
  emotechat:
    description: Toggles Bedrock Player emote chat for Java Players.
    usage: /<command>
    permission: geyserextras.emotechat
    aliases:
      - muteemotechat
permissions:
  geyserextras.menu:
    default: true
    description: Allow players to execute the /geyserextras command
  geyserextras.platformlist:
    default: true
    description: Allow players to execute the /platformlist command
  geyserextras.playerlist:
    default: true
    description: Allow players to execute the /playerlist command
  geyserextras.emotechat:
    default: true
    description: Allow players to execute the /emotechat command
